FROM node:18

WORKDIR /home/node/app

COPY package*.json ./

ARG API_URL
ARG SESSION_SECRET
ARG FRONTEND_URL
ARG OPENAI_API_KEY

ENV API_URL ${API_URL}
ENV SESSION_SECRET=${SESSION_SECRET}
ENV FRONTEND_URL=${FRONTEND_URL}
ENV OPENAI_API_KEY=${OPENAI_API_KEY}

RUN npm install

COPY . .

EXPOSE 3000

CMD [ "npm", "start" ]